# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arcondicionado.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("arcondicionado.proto", :syntax => :proto3) do
    add_message "Arcond" do
      optional :on_off, :bool, 1
      optional :temperatura, :int32, 2
    end
  end
end

Arcond = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Arcond").msgclass
