# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tv.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tv.proto", :syntax => :proto3) do
    add_message "Tv" do
      optional :comando, :enum, 1, "Tv.Comando"
      optional :estado, :bool, 2
      optional :canal, :int32, 3
    end
    add_enum "Tv.Comando" do
      value :null, 0
      value :getEstado, 1
      value :setEstado, 2
      value :getCanal, 3
      value :setCanal, 4
    end
  end
end

Tv = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tv").msgclass
Tv::Comando = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Tv.Comando").enummodule
